Reworked ModelArchive.downloadModel
There were several issues in the existing code.

* The errors were sometimes wrong and very confusing:
Error thrown for an existing local model file:
>org.pytorch.serve.archive.ModelNotFoundException: Model not found at: /tmp/inputs/Model_archive/data

Errors for disallowed URLs are also very confusing.

* Loading from local directory was supported (https://github.com/pytorch/serve/issues/721), but not loading from a local file, which was failing with confusing error above

This PR fixes the bugs, improves the error reporting and streamlines the loading code.